package io.goodforgod.dummymaker.bundle;

import java.util.Arrays;
import java.util.List;

/**
 * @author Anton Kurako (GoodforGod)
 * @since 25.08.2022
 */
public final class MerchantBundle extends AbstractBundle {

    private static final List<String> BUNDLE_ENGLISH = Arrays.asList(
            "Contractors–Residential and Commercial", "Air Conditioning", "Heating and Plumbing Contractors",
            "Electrical Contractors", "Insulation", "Masonry", "Plastering", "Stonework and Tile Setting Contractors",
            "Carpentry Contractors", "Roofing and Siding", "Sheet Metal Work Contractors", "Concrete Work Contractors",
            "Contractors", "Special Trade Contractors", "Miscellaneous Publishing and Printing", "Typesetting",
            "Plate Making and Related Services", "Sanitation", "Polishing and Specialty Cleaning Preparations",
            "Railroads–Freight", "Transportation–Suburban and Local Commuter Passenger", "including Ferries",
            "Passenger Railways", "Ambulance Services", "Taxicabs and Limousines", "Bus Lines", "Motor Freight Carriers",
            "Moving and Storage Companies", "Local Delivery", "Courier Services–Air and Ground", "Freight Forwarders",
            "Public Warehousing–Farm Products", "Refrigerated Goods", "Household Goods Storage", "Cruise Lines",
            "Boat Leases and Boat Rentals", "Marinas", "Marine Supplies", "Air Carriers", "Airlines", "Airports",
            "Airport Terminals", "Flying Fields", "Travel Agencies and Tour Operators", "Package Tour Operators",
            "Telemarketing of Travel Related Services and Vitamins", "Bridge and Road Fees", "Tolls",
            "Transportation Services Not Elsewhere Classified", "Telecommunication Equipment Including Telephone Sales",
            "Telecommunication Services including but not limited to prepaid phone services and recurring phone services",
            "Computer Information Services", "Telegraph Services", "Wire Transfer Money Orders", "Money Transfer", "Cable",
            "Satellite", "and Other Pay Television and Radio Services", "Utilities–Electric", "Gas", "Heating Oil", "Sanitary",
            "Water", "Motor Vehicle Supplies and New Parts", "Office and Commercial Furniture",
            "Construction Materials Not Elsewhere Classified", "Office", "Photographic", "Photocopy and Microfilm Equipment",
            "Computers", "Computer Peripheral Equipment", "Software", "Commercial Equipment Not Elsewhere Classified",
            "Hospital Equipment and Supplies", "Metal Service Centers and Offices", "Electrical Parts and Equipment",
            "Hardware Equipment and Supplies", "Plumbing and Heating Equipment", "Industrial Supplies Not Elsewhere Classified",
            "Precious Stones and Metals", "Watches and Jewelry", "Durable Goods Not Elsewhere Classified", "Stationery",
            "Office Supplies", "Printing and Writing Paper", "Drugs", "Drug Proprietors and Druggists Sundries", "Piece Goods",
            "Notions", "and Other Dry Goods", "Mens", "Womens and Childrens Uniforms and Commercial Clothing",
            "Commercial Footware", "Chemicals and Allied Products Not Elsewhere Classified", "Petroleum and Petroleum Products",
            "Books", "Periodicals and Newspapers", "Florists Supplies", "Nursery Stock and Flowers", "Paints",
            "Varnishes and Supplies", "Non-Durable Goods Not Elsewhere Classified", "Home Supply Warehouse Stores",
            "Building Materials", "Lumber Stores", "Glass", "Paint", "Wallpaper Stores", "Hardware Stores",
            "Lawn and Garden Supply Stores", "Mobile Home Dealers", "Warehouse Club Gas", "Wholesale Clubs", "Duty Free Stores",
            "Discount Stores", "Department Stores", "Variety Stores", "Miscellaneous General Merchandise Stores",
            "Grocery Stores", "Supermarkets", "Freezer and Locker Meat Provisioners", "Candy", "Nut and Confectionery Stores",
            "Dairy Products Stores", "Bakeries", "Miscellaneous Food Stores–Convenience Stores", "Markets", "Specialty Stores",
            "and Vending Machines", "Automobile and Truck Dealers–Sales", "Repairs", "Parts and Leasing",
            "Automobile and Truck Dealers", "Automotive Tire Stores", "Automotive Parts and Accessories Stores",
            "Service Stations", "Fuel Dispenser", "Automated", "Boat Dealers", "Camper Dealers",
            "Recreational and Utility Trailers", "Motorcycle Shops and Dealers", "Motor Home Dealers", "Snowmobile Dealers",
            "Miscellaneous Automotive", "Aircraft", "and Farm Equipment Dealers", "Mens and Boys Clothing and Accessories Stores",
            "Womens Ready to Wear Stores", "Womens Accessory and Specialty Stores", "Childrens and Infants Wear Stores",
            "Family Clothing Stores", "Sports Apparel", "and Riding Apparel Stores", "Shoe Stores", "Furriers and Fur Shops",
            "Mens and Womens Clothing Stores", "Alterations", "Mending", "Seamstresses", "Tailors", "Wig and Toupee Shops",
            "Accessory and Apparel Stores–Miscellaneous", "Equipment", "Furniture and Home Furnishings Stores",
            "Floor Covering Stores", "Drapery", "Upholstery and Window Coverings Stores", "Fireplace",
            "Fireplace Screens and Accessories Stores", "Miscellaneous House Furnishing Specialty Shops",
            "Household Appliance Stores", "Electronics Sales", "Music Stores–Musical Instruments", "Pianos and Sheet Music",
            "Computer Software Stores", "Record Shops", "Caterers", "Eating Places and Restaurants", "Bars", "Cocktail Lounges",
            "Discotheques", "Nightclubs and Taverns–Drinking Places", "Fast Food Restaurants", "Digital Goods: Books", "Movies",
            "Music", "Digital Goods: Games", "Digital Goods: Applications", "Digital Goods: Large Digital Goods Merchant ",
            "Digital Goods: Multi-Category", "Drug Stores and Pharmacies", "Package Stores–Beer", "Wine and Liquor",
            "Second Hand Stores", "Used Merchandise Stores", "Antique Shops–Sales", "Repairs and Restoration Services",
            "Pawn Shops", "Wrecking and Salvage Yards", "Antique Reproduction Stores", "Bicycle Shops–Sales and Service",
            "Sporting Goods Stores", "Book Stores", "Office", "School Supply and Stationery Stores", "Clock", "Jewelry",
            "Watch and Silverware Stores", "Game", "Toy and Hobby Shops", "Camera and Photographic Supply Stores", "Card", "Gift",
            "Novelty and Souvenir Shops", "Leather Goods and Luggage Stores", "Fabric", "Needlework",
            "Piece Goods and Sewing Stores", "Crystal and Glassware Stores", "Direct Marketing Insurance Services",
            "Mail Order Houses Including Catalog Order Stores", "Direct Marketing–Travel Related Arrangement Services",
            "Door-to-Door Sales", "Direct Marketing–Catalog Merchants",
            "Direct Marketing–Combination Catalog and Retail Merchant", "Direct Marketing–Outbound Telemarketing Merchants",
            "Direct Marketing–Inbound Telemarketing Merchants", "Direct Marketing–Continuity",
            "Direct Marketing–Other Direct Marketers", "Artist Supply Stores", "Craft Shops", "Art Dealers and Galleries",
            "Stamp and Coin Stores–Philatelic and Numismatic Supplies", "Religious Goods Stores", "Rubber Stamp Store",
            "Hearing Aids–Sales", "Supply Stores", "Orthopedic Goods–Artificial Limb Stores", "Cosmetic Stores",
            "Typewriter Stores–Rentals", "Sales", "Fuel Dealers–Coal", "Fuel Oil", "Liquefied Petroleum", "Wood", "Florists",
            "Cigar Stores and Stands", "News Dealers and Newsstands", "Pet Shops", "Pet Food and Supplies",
            "Swimming Pools–Sales and Supplies", "Electric Razor Stores–Sales and Service", "Tent and Awning Shops",
            "Miscellaneous and Specialty Retail Stores", "Member Financial Institution",
            "Quasi Cash–Member Financial Institution", "Quasi Cash–Merchant", "Securities–Brokers and Dealers",
            "Aero Servicio Carabobo", "Insurance Sales", "Underwriting and Premiums", "Insurance–Premiums",
            "Real Estate Agents and Managers–Rentals", "Remove Stored Value Load", "Value Purchase–Member Financial Institution",
            "MoneySend Intercountry", "MoneySend Funding", "Funding Transaction", "POI Funding Transactions", "Overpayments",
            "Savings Bonds", "Lodging–Hotels", "Motels", "Resorts", "Timeshares", "Sporting and Recreational Camps",
            "Campgrounds and Trailer Parks", "Cleaning", "Garment and Laundry Services", "Laundry Services–Family and Commercial",
            "Dry Cleaners", "Carpet and Upholstery Cleaning", "Photographic Studios", "Barber and Beauty Shops",
            "Hat Cleaning Shops", "Shoe Repair Shops", "Shoe Shine Parlors", "Funeral Service and Crematories", "Dating Services",
            "Tax Preparation Service", "Debt", "Marriage", "Personal–Counseling Services", "Shopping Clubs", "Services",
            "Hospital Patient-Personal Funds Withdrawal", "Babysitting Services", "Clothing Rental–Costumes",
            "Uniforms and Formal Wear", "Massage Parlors", "Health and Beauty Spas", "Other Services", "Advertising Services",
            "Consumer Credit Reporting Agencies", "Blueprinting and Photocopying Services", "Commercial Art", "Graphics",
            "Photography", "Quick Copy", "Reproduction and Blueprinting Services",
            "Stenographic and Secretarial Support Services", "Exterminating and Disinfecting Services",
            "Cleaning and Maintenance", "Janitorial Services", "Employment Agencies and Temporary Help Services",
            "Computer Programming", "Data Processing and Integrated System Design Services", "Information Retrieval Services",
            "Computer Maintenance", "Repair And Services", "Consulting", "Management and Public Relations Services",
            "Detective Agencies", "Protective Agencies", "Security Services including Armored Cars", "Guard Dogs",
            "Equipment Rental and Leasing Services", "Furniture Rental", "Tool Rental", "Photo Developing",
            "Photofinishing Laboratories", "Business Services Not Elsewhere Classified", "Automobile Rental Agency",
            "Truck Rental", "Motor Home and Recreational Vehicle Rental", "Automobile Parking Lots and Garages",
            "Express Payment Service Merchants–Parking Lots and Garages", "Automotive Body Repair Shops",
            "Tire Retreading and Repair Shops", "Automotive Paint Shops", "Automotive Service Shops", "Car Washes",
            "Towing Services", "Electronic Repair Shops", "Air Conditioning and Refrigeration Repair Shops",
            "Appliance Repair Shops", "Electrical and Small", "Clock", "Jewelry and Watch Repair Shops", "Furniture–Reupholstery",
            "Repair and Refinishing", "Welding Repair", "Miscellaneous Repair Shops and Related Services",
            "Government Owned Lottery", "Government-Licensed Casinos", "Government-Licensed Horse Racing",
            "Motion Picture and Video Tape Production and Distribution", "Motion Picture Theaters",
            "Express Payment Service — Motion Picture Theater", "Video Tape Rental Stores", "Dance Halls", "Schools and Studios",
            "Theatrical Producers", "Ticket Agencies", "Bands",
            "Orchestras and Miscellaneous Entertainers– Not Elsewhere Classified", "Pool and Billiard Establishments",
            "Bowling Alleys", "Athletic Fields", "Commercial Sports", "Professional Sports Clubs", "Sports Promoters",
            "Tourist Attractions and Exhibits", "Golf Courses", "Public", "Video Amusement Game Supplies",
            "Video Game Arcades and Establishments", "Gambling Transactions", "Betting Sportsbook", "fantasy",
            "social gaming; when regulated and not covered by other MCCs", "Amusement Parks", "Carnivals", "Circuses",
            "Carnivals", "Fortune Tellers", "Clubs–Country Clubs", "Membership Athletic", "Recreation", "Sports",
            "Private Golf Courses", "Aquariums", "Dolphinariums", "Zoos and Seaquariums", "Recreation Services", "Doctors",
            "Dentists and Orthodontists", "Osteopathic Physicians", "Chiropractors", "Optometrists and Ophthalmologists",
            "Opticians", "Optical Goods and Eyeglasses", "Chiropodists", "Podiatrists", "Nursing and Personal Care Facilities",
            "Hospitals", "Dental and Medical Laboratories", "Health Practitioners", "Medical Services", "Attorneys",
            "Legal Services", "Elementary and Secondary", "Colleges", "Universities", "Professional Schools and Junior Colleges",
            "Schools", "Correspondence", "Business and Secretarial", "Trade and Vocational", "Schools And Educational Services",
            "Child Care Services", "Organizations", "Charitable and Social Service", "Social and Fraternal", "Political",
            "Religious", "Automobile Associations", "Membership", "Testing Laboratories", "Architectural",
            "Engineering and Surveying Services", "Accounting", "Auditing and Bookkeeping Services", "Professional Services",
            "I-Purchasing Pilot", "Court Costs Including Alimony and Child Support", "Fines", "Bail and Bond Payments",
            "Tax Payments", "Government Services", "I-Purchasing Pilot", "Postal Services–Government Only",
            "Intra-Government Purchases–Government Only", "Automated Referral Service", "Visa Credential Server",
            "GCAS Emergency Services", "UK Supermarkets", "Electronic Hot File", "UK Petrol Stations", "Electronic Hot File",
            "Gambling-Horse", "Dog Racing", "State Lottery", "Intra-Company Purchases", "Veterinary Services",
            "Agricultural Cooperatives", "Horticultural and Landscaping Services");

    private static final List<String> BUNDLE_RUSSIAN = Arrays.asList(
            "Подрядчики – жилые и коммерческие", "Кондиционеры", "Подрядчики по отоплению и сантехнике",
            "Электрические подрядчики", "Изоляция", "Кладка", "Штукатурка", "Подрядчики по каменной кладке и укладке плитки",
            "Подрядчики по столярным работам", "Кровельные и сайдинговые подрядчики", "Подрядчики по работе с листовым металлом",
            "Подрядчики по бетонным работам", "Подрядчики", "Специальные торговые подрядчики",
            "Разное издательское дело и печать", "Наборный набор", "Изготовление плит и сопутствующие услуги", "Санитария",
            "Полировка и специальная уборка  Подготовка", "Железные дороги – Грузы",
            "Транспорт – Пригородный и местный пригородный пассажир", "В том числе паромы", "Пассажирские железные дороги",
            "Услуги скорой помощи", "Такси и лимузины", "Автобусные линии", "Автомобильные грузовые перевозчики",
            "Движущиеся и складские компании", "Местная доставка", "Курьерские услуги – воздушные и наземные", "Экспедиторы",
            "Общественное складирование – сельскохозяйственная продукция", "Рефрижераторные товары",
            "Хранение хозяйственных товаров", "Круизные линии", "Аренда лодок и аренда лодок", "Марины", "Морские поставки",
            "Воздушные поставки", "Воздушные перевозки", "Воздушные перевозки", "Перевозчики", "Авиакомпании", "Аэропорты",
            "Терминалы аэропортов", "Летающие поля", "Туристические агентства и туроператоры", "Пакетные туроператоры",
            "Телемаркетинг туристических услуг и витаминов", "Мостовые и дорожные сборы", "Дорожные сборы",
            "Транспортные услуги, не классифицированные в других местах",
            "Телекоммуникационное оборудование, включая телефонные продажи",
            "Телекоммуникационные услуги, включая, но не ограничиваясь, предоплаченные телефонные услуги и повторяющиеся телефонные услуги",
            "Компьютерные информационные услуги", "Телеграфные услуги", "Услуги", "Денежные переводы банковским переводом",
            "Денежные переводы", "Кабельные", "Спутниковые", "И другие платные телерадиослуги",
            "Коммунальные услуги – электрические", "Газ", "Мазут", "Санитарные", "Вода",
            "Автомобильные принадлежности и новые детали", "Офисная и коммерческая мебель",
            "Строительные материалы, не классифицированные в другом месте", "Офисные", "Фотографические",
            "Фотокопировальное и микрофильмическое оборудование", "Компьютеры", "Компьютерное периферийное оборудование",
            "Программное обеспечение", "Коммерческое оборудование, не классифицированное в другом месте", "Больница",
            "Оборудование и расходные материалы", "Металлосервисные центры и офисы", "Электрические детали и оборудование",
            "Аппаратное оборудование и расходные материалы", "Сантехническое и отопительное оборудование",
            "Промышленные принадлежности, не отнесенные к другим категориям", "Драгоценные камни и металлы",
            "Часы и ювелирные изделия", "Товары длительного пользования, не классифицированные в другом месте",
            "Канцелярские принадлежности", "Канцелярские принадлежности", "Печатная и письменная бумага", "Лекарства",
            "Наркоторговцы и аптекари", "Штучные товары", "Понятия", "и другие сухие товары", "Мужская",
            "Женская и детская униформа и коммерческая одежда", "Коммерческая обувь",
            "Химикаты и сопутствующие товары, не классифицированные в других местах", "Нефть и нефтепродукты", "Книги",
            "Периодические издания и газеты", "Флористические принадлежности", "Питомники и цветы", "Краски",
            "Лаки и принадлежности", "Товары недлительного пользования, не классифицированные в другом месте",
            "Складские магазины товаров для дома", "Строительные материалы", "Магазины пиломатериалов", "Стекло", "Краски",
            "Магазины обоев", "Хозяйственные магазины", "Газоны и сады", "Магазины снабжения", "Дилеры мобильных домов",
            "Складской клуб газа", "Оптовые клубы", "Магазины беспошлинной торговли", "Дисконтные магазины", "Универмаги",
            "Магазины разнообразных товаров", "Магазины разных товаров общего назначения", "Продуктовые магазины", "Супермаркеты",
            "Морозильные и шкафчики мясные провизии", "Конфеты", "Магазины орехов и кондитерских изделий",
            "Магазины молочных продуктов", "Пекарни", "Разные продовольственные магазины-магазины", "Рынки",
            "Специализированные магазины", "И торговые автоматы", "Дилеры автомобилей и грузовиков", "Ремонт",
            "Запчасти и лизинг", "Дилеры автомобилей и грузовиков", "Магазины автомобильных шин",
            "Магазины автомобильных запчастей и аксессуаров", "Станции технического обслуживания", "Топливораздаточные колонки",
            "Автоматизированные", "Дилеры лодок", "Дилеры кемперов", "Рекреационные и коммунальные прицепы",
            "Мотоциклетные магазины и дилеры", "Дилеры автодома", "Дилеры снегоходов", "Разное автомобильное", "Авиационные",
            "И фермерские торговцы", "Магазины одежды и аксессуаров для мужчин и мальчиков",
            "Магазины готовой одежды и аксессуаров для женщин", "Магазины аксессуаров и специализированных товаров для женщин",
            "Магазины одежды для детей и младенцев", "Магазины семейной одежды", "Магазины спортивной одежды",
            "Магазины одежды для верховой езды", "Обувные магазины", "Магазины скорняков и меха",
            "Магазины мужской и женской одежды", "Переделки", "Починки", "Швеи", "Портные", "Магазины париков и тупи",
            "Магазины аксессуаров и одежды – разное", "Оборудование", "Магазины мебели и предметов интерьера",
            "Магазины напольных покрытий", "Драпировки", "Магазины обивки и оконных покрытий", "Камин",
            "Магазины каминных экранов и аксессуаров", "Специализированные магазины по обустройству разных домов",
            "Магазины бытовой техники", "Продажа электроники", "Музыкальные магазины – музыкальные инструменты", "Пианино и ноты",
            "Магазины компьютерного программного обеспечения", "Музыкальные магазины", "Музыкальные магазины",
            "Магазины общественного питания", "Рестораны общественного питания", "Рестораны питания и рестораны", "Бары",
            "Коктейль-лаунжи", "Дискотеки", "Ночные клубы и таверны – питейные заведения", "Рестораны быстрого питания",
            "Цифровые товары: книги", "Фильмы", "Музыка", "Цифровые товары: игры", "Цифровые игры",
            "Цифровые  Товары: Приложения", "Цифровые товары: Крупный торговец цифровыми товарами",
            "Цифровые товары: мультикатегории", "Аптеки и аптеки", "Магазины упаковки – пиво", "Вино и ликер",
            "Магазины подержанных товаров", "Магазины подержанных товаров", "Антикварные магазины – продажи",
            "Ремонтные и реставрационные услуги", "Ломбарды", "Мусорные и спасательные дворы", "Антикварные магазины репродукции",
            "Магазины велосипедов – продажа и обслуживание", "Магазины спортивных товаров", "Книжные магазины", "Офис",
            "Магазины школьных товаров и канцелярских товаров", "Часы", "Ювелирные изделия", "Магазины часов и столового серебра",
            "Игровые", "Магазины игрушек и хобби", "Магазины фотоаппаратов и фототоваров", "Карточные", "Подарочные",
            "Магазины новинок и сувениров", "Магазины кожаных изделий и чемоданов", "Магазины тканей", "Рукоделия",
            "Штучные товары и швейные магазины", "Магазины хрусталя и стеклянной посуды",
            "Услуги по страхованию прямого маркетинга", "Почтовые заказные дома, включая магазины заказов по каталогу",
            "Услуги по организации прямого маркетинга и путешествий", "Продажи от двери до двери",
            "Прямой маркетинг – Продавцы каталога", "Прямой маркетинг – Комбинированный каталог и розничный торговец",
            "Прямой маркетинг – Исходящие торговцы телемаркетингом", "Прямой маркетинг – Входящие торговцы телемаркетингом",
            "Прямой маркетинг – Непрерывность", "Прямой маркетинг – Другие прямые маркетологи", "Магазины товаров для художников",
            "Ремесленные магазины", "Арт-дилеры и галереи",
            "Магазины марок и монет – филателистические и нумизматические принадлежности", "Магазины религиозных товаров",
            "Магазин резиновых штампов", "Слуховые аппараты – продажи", "Магазины снабжения",
            "Магазины ортопедических изделий – искусственных конечностей", "Косметические магазины",
            "Магазины пишущих машинок – Аренда", "Продажи", "Топливные дилеры – уголь", "Мазут", "Сжиженная нефть", "Древесина",
            "Флористы", "Сигарные магазины и киоски", "Дилеры новостей и газетные киоски", "Зоомагазины",
            "Корма для домашних животных и расходные материалы", "Бассейны – продажи и расходные материалы",
            "Магазины электробритвы – продажи и обслуживание", "Палаточные и тентовые магазины",
            "Разные и специализированные розничные магазины", "Финансовое учреждение-член",
            "Quasi Cash – Финансовое учреждение-член", "КвазиДенежный – Торговец", "Ценные бумаги – брокеры и дилеры",
            "Aero Servicio Carabobo", "Страховые продажи", "Андеррайтинг и премии", "Страхование – премии",
            "Агенты по недвижимости и менеджеры по аренде", "Удалить накопленную ценностную нагрузку",
            "Финансовое учреждение,член стоимостной покупки", "MoneySend Intercountry", "Финансирование MoneySend",
            "Сделка по финансированию", "Операции по финансированию POI", "Переплаты", "Сберегательные облигации", "Жилье –Отели",
            "Мотели", "Курорты", "Таймшеры", "Спортивные и рекреационные лагеря", "Кемпинги и трейлерные парки", "Уборка",
            "Услуги швейной и прачечной", "Услуги прачечной – семейные и коммерческие", "Химчистки", "Чистка ковров и обивки",
            "Фотостудии", "Парикмахерские и салоны красоты", "Магазины по чистке шляп", "Мастерские по ремонту обуви",
            "Салоны чистки обуви", "Похоронные услуги и крематории", "Службы знакомств", "Служба подготовки налогов", "Долг",
            "Брак", "Персональные консультации", "Торговые клубы", "Услуги", "Снятие средств с пациентов больницы", "Услуги няни",
            "Аренда одежды – костюмы", "Униформа и формальная одежда", "Массажные салоны", "Спа-салоны здоровья и красоты",
            "Другие услуги", "Рекламные услуги", "Агентства по отчетности о потребительском кредите",
            "Услуги по проектированию и фотокопированию", "Коммерческое искусство", "Графика", "Фотография",
            "Быстрое копирование", "Услуги по воспроизведению и проектированию",
            "Услуги стенографической и секретарской поддержки", "Услуги по уничтожению и дезинфекции", "Уборка и дезинфекция",
            "Уборка и  Техническое обслуживание", "Услуги по уборке", "Агентства по трудоустройству и служба временной помощи",
            "Компьютерное программирование", "Услуги по обработке данных и комплексному проектированию систем",
            "Услуги по поиску информации", "Обслуживание компьютеров", "Ремонт и услуги", "Консалтинг",
            "Услуги по управлению и связям с общественностью", "Детективные агентства", "Охранные агентства",
            "Службы безопасности, включая бронеавтомобили", "Сторожевые собаки", "Услуги по аренде и лизингу оборудования",
            "Аренда мебели", "Аренда инструмента", "Фото  Разработка", "Лаборатории фотофинишеринга",
            "Бизнес-услуги, не классифицированные в других местах", "Агентство по прокату автомобилей",
            "Аренда грузовых автомобилей", "Аренда автодомов и рекреационных транспортных средств",
            "Автомобильные парковки и гаражи", "Торговцы услугами экспресс-оплаты – автостоянки и гаражи",
            "Автомобильные мастерские кузовного ремонта", "Мастерские по восстановлению протектора и ремонту шин",
            "Автомобильные лакокрасочные мастерские", "Автосервисы", "Автомойки", "Буксировочные услуги",
            "Электронные ремонтные мастерские", "Кондиционирование воздуха и холодильное оборудование", "Ремонтные мастерские",
            "Мастерские по ремонту бытовой техники", "Электрические и малые", "Часы", "Ювелирные и часовые мастерские",
            "Мебельно-переобивочные", "Ремонт и отделка", "Ремонт сварочной техники",
            "Различные ремонтные мастерские и сопутствующие услуги", "Государственная лотерея",
            "Лицензированные правительством казино", "Государственные лицензированные скачки",
            "Производство и распространение кино- и видеокассет", "Кинотеатры кино- и видеокассет",
            "Услуги экспресс-оплаты — кинотеатры", "Магазины проката видеокассет", "Танцевальные залы", "Школы и студии",
            "Театральные продюсеры", "Билетные агентства", "Группы",
            "Оркестры и разные артисты – не классифицированные в другом месте", "Бильярдные и бильярдные заведения", "Боулинг",
            "Спортивные площадки", "Коммерческие виды спорта", "Профессиональные спортивные клубы", "Спортивные промоутеры",
            "Туристические достопримечательности и экспонаты", "Поля для гольфа", "Общественные", "Принадлежности для видеоигр",
            "Аркады и заведения для видеоигр", "Азартные игры", "Азартные игры", "Букмекерская контора", "Фэнтези",
            "социальные игры; когда регулируется и не охватывается другими ЦУП", "Парки развлечений", "Карнавалы", "Цирки",
            "Карнавалы", "Гадалки", "Клубы–Загородные клубы", "Членство в спортивных", "Рекреационных", "Спортивных",
            "Частных полях для гольфа", "Аквариумы", "Дельфинарии", "Зоопарки и океанариумы", "Рекреационные услуги", "Врачи",
            "Стоматологи и ортодонты", "Врачи-остеопаты", "Хиропрактики", "Оптометристы и офтальмологи", "Оптики",
            "Оптические товары и очки", "Хироподисты", "Ортопеды", "Ортопеды", "Медсестры", "Учреждения личной гигиены",
            "Больницы", "Стоматологические и медицинские лаборатории", "Практикующие врачи", "Медицинские услуги", "Адвокаты",
            "Юридические услуги", "Начальные и средние", "Колледжи", "Университеты", "Профессиональные школы и младшие колледжи",
            "Школы", "Заочная", "Бизнес и секретарь", "Торговля и профессиональное производство",
            "Школы и образовательные услуги", "Услуги по уходу за детьми", "Организации", "Благотворительная и социальная служба",
            "Социальные и братские", "Политические", "Религиозные", "Автомобильные ассоциации", "Членство",
            "Испытательные лаборатории", "Архитектурные", "Инженерные и геодезические услуги", "Бухгалтерский учет",
            "Аудиторские и бухгалтерские услуги", "Профессиональные услуги", "Пилотный проект по i-закупкам",
            "Судебные издержки, включая алименты и поддержку детей", "Штрафы", "Выплаты залога и облигаций", "Налоговые платежи",
            "Государственные услуги", "Пилот по I-закупкам", "Почтовые услуги — только правительство",
            "Внутригосударственные закупки — только правительство", "Автоматизированная справочная служба",
            "Визовые учетные данные", "Сервер", "GCAS Emergency Services", "Супермаркеты Великобритании",
            "Электронный горячий файл", "Автозаправочные станции Великобритании", "Электронный горячий файл", "Игорная лошадь",
            "Собачьи бега", "Государственная лотерея", "Внутрифирменные закупки", "Ветеринарные услуги",
            "Сельскохозяйственные кооперативы", "Услуги садоводства и ландшафтного дизайна");

    @Override
    List<String> getEnglish() {
        return BUNDLE_ENGLISH;
    }

    @Override
    List<String> getRussian() {
        return BUNDLE_RUSSIAN;
    }
}
